# Generated by Django 4.0.5 on 2022-06-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0004_alter_totem_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totem',
            name='paciente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='totem',
            name='senha',
            field=models.CharField(max_length=200),
        ),
    ]
