# Generated by Django 4.0.5 on 2022-06-23 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0009_alter_totem_horario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totem',
            old_name='horario',
            new_name='data',
        ),
    ]
